---
name: Get Images for Build
description: Get Images for Build
inputs:
  image_flavor:
    description: "Types of Image to Build (Bazzite, Desktop, Server)"
    required: true
outputs:
  images:
    description: "List of Images that will be built"
    value: ${{ steps.images.outputs.images }}
runs:
  using: "composite"
  steps:
    - name: Get Images for Build
      id: images
      shell: bash
      run: |-
        # Array to Hold Image Names
        images=()

        # Add Images
        case "${{ inputs.image_flavor }}" in
        "Bazzite")
          images+=("bazzite" "bazzite-nvidia")
          #images+=("bazzite-deck" "bazzite-deck-nvidia")
          ;;
        "Bluefin")
          images+=("bluefin" "bluefin-nvidia")
          images+=("bluefin-latest" "bluefin-latest-nvidia")
          images+=("bluefin-gdx" "bluefin-lts")
          ;;
        "Server")
          images+=("ucore-minimal" "ucore" "ucore-nvidia")
          images+=("ucore-hci" "ucore-hci-nvidia")
          ;;
        esac

        # Make into Json Array
        images="$(jq --null-input --compact-output '$ARGS.positional' \
        --args "${images[@]}")"

        # Output
        echo "images=$images" >> "$GITHUB_OUTPUT"
