name: mcOS Build Desktop
on:
  schedule:
    - cron: "41 6 * * *"  # 6:41 UTC
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
jobs:
  build-image:
    name: Build Images
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        image_flavor: ["Bluefin", "Aurora"]
    with:
      image_flavor: ${{ matrix.image_flavor }}